# Generated by Django 4.1.6 on 2023-02-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('district_Name', models.CharField(max_length=200)),
                ('PS_Name', models.CharField(max_length=200)),
                ('fir_no', models.CharField(max_length=200)),
                ('fir_date', models.DateField()),
                ('person_No', models.CharField(max_length=200)),
                ('arrest_Date', models.DateField()),
                ('father_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('ageWhileOpening', models.DateField()),
                ('age', models.DateField()),
                ('pres_address1', models.TextField(max_length=200)),
                ('perm_address1', models.TextField(max_length=200)),
                ('person_status', models.CharField(max_length=200)),
                ('major_head', models.CharField(max_length=200)),
                ('minor_head', models.CharField(max_length=200)),
                ('crime_no', models.DateField()),
                ('arr_id', models.DateField()),
                ('unit_id', models.DateField()),
                ('fir_id', models.DateField()),
                ('dedt', models.DateField()),
            ],
        ),
    ]
